// HEADER
export const CHANGE_SEARCH_HEADER = "CHANGE_SEARCH_HEADER";

// SALES
export const SALES_LOADING = "SALES_LOADING";
export const SALES_ERROR = "SALES_ERROR";
export const SALES_OK = "SALES_OK";

// CATEGORIES
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";
export const CATEGORIES_OK = "CATEGORIES_OK";

// ITEMS
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_SEARCH_CATALOG = "CHANGE_SEARCH_CATALOG";
export const CLEAN_ITEMS = "CLEAN_ITEMS";
export const ITEMS_LOADING = "ITEMS_LOADING";
export const ITEMS_ERROR = "ITEMS_ERROR";
export const ITEMS_OK = "ITEMS_OK";
