export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";
export const CATEGORIES_OK = "CATEGORIES_OK";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
